export enum CONTAINER_TYPE {
	userRegisterController = 'userRegisterController',
	userLoginController = 'userLoginController',
	userRegisterUseCase = 'userRegisterUseCase',
	userLoginUseCase = 'userLoginUseCase',
	userRepository = 'userRepository',
	/* ===================== category ======================== */
	categoryCreateController = 'categoryCreateController',
	categoryFindByIdController = 'categoryFindByIdController',
	categoryDeleteController = 'categoryDeleteController',
	categoryUpdateController = 'categoryUpdateController',
	categoryFindAllController = 'categoryFindAllController',
	categoryFindCounterController = 'categoryFindCounterController',
	categoryCreateUseCase = 'categoryCreateUseCase',
	categoryFindByIdUseCase = 'categoryFindByIdUseCase',
	categoryDeleteUseCase = 'categoryDeleteUseCase',
	categoryUpdateUseCase = 'categoryUpdateUseCase',
	categoryFindAllUseCase = 'categoryFindAllUseCase',
	categoryRepository = 'categoryRepository',
	/* ===================== category ======================== */
	productCreateController = 'productCreateController',
	productFindByIdController = 'productFindByIdController',
	productDeleteController = 'productDeleteController',
	productUpdateController = 'productUpdateController',
	productFindAllController = 'productFindAllController',
	/*==================== Product usecase==================== */
	productCreateUseCase = 'productCreateUseCase',
	productFindByIdUseCase = 'productFindByIdUseCase',
	productDeleteUseCase = 'productDeleteUseCase',
	productUpdateUseCase = 'productUpdateUseCase',
	productFindAllUseCase = 'productFindAllUseCase',
	productRepository = 'productRepository',
	/* ===================== product ========================*/
	eventBus = 'eventBus',
	categoryCreatedHandler = 'categoryCreatedHandler',
	rabbitMqEventBus = 'rabbitMqEventBus',
	rabbitMQConnection = 'rabbitMQConnection',
	rabbitMQQueueFormatter = 'rabbitMQQueueFormatter',
	rabbitMQConfigFactory = 'rabbitMQConfigFactory',
	rabbitMQConfigurer = 'rabbitMQConfigurer',
	domainEventFailoverPublisher = 'domainEventFailoverPublisher',
	domainEventDeserializer = 'domainEventDeserializer',
	/* ===================== CQRS =========================*/
	commandHandlers = 'commandHandlers',
	commandBus = 'commandBus',
	queryHandlers = 'queryHandlers',
	queryBus = 'queryBus',
	categoryFindCounter = 'categoryFindCounter',
}
