"use strict";
exports.__esModule = true;
exports.categoryRoutes = void 0;
var express_1 = require("express");
var category_delete_controller_1 = require("../controllers/category/category-delete.controller");
var container_1 = require("../dependency-injection/container");
var container_types_1 = require("../dependency-injection/container.types");
var router = (0, express_1.Router)();
var categoryCreateController = container_1.container.resolve(container_types_1.containerTypes.categoryCreateController);
var categoryFindAllController = container_1.container.resolve(container_types_1.containerTypes.categoryFindAllController);
var categoryFindByIdController = container_1.container.resolve(container_types_1.containerTypes.categoryFindByIdController);
var categoryUpdateController = container_1.container.resolve(container_types_1.containerTypes.categoryUpdateController);
var categoryDeleteController = container_1.container.resolve(category_delete_controller_1.CategoryDeleteController);
router.post('/', categoryCreateController.execute.bind(categoryCreateController));
router.get('/all', categoryFindAllController.execute.bind(categoryFindAllController));
router.get('/:id', categoryFindByIdController.execute.bind(categoryFindByIdController));
router.put('/:id', categoryUpdateController.execute.bind(categoryUpdateController));
router["delete"]('/:id', categoryDeleteController.execute.bind(categoryDeleteController));
exports.categoryRoutes = router;
